import type { IconType } from "react-icons";
import {
  SiTypescript,
  SiJavascript,
  SiPython,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiNodedotjs,
  SiPostgresql,
  SiMongodb,
  SiGit,
  SiDocker,
  SiFigma,
  SiTensorflow,
  SiCplusplus,
  SiHtml5,
  SiCss3,
  SiFirebase,
  SiVercel,
  SiLinux,
  SiGraphql,
  SiRedis,
  SiRust,
  SiGo,
  SiKubernetes,
  SiPrisma,
  SiSvelte,
  SiVuedotjs,
  SiAmazon,
  SiGooglecloud,
  SiSupabase,
  SiNestjs,
  SiExpress,
  SiSwift,
  SiKotlin,
  SiFlutter,
  SiDart,
  SiPhp,
  SiRuby,
  SiOpenai,
  SiPytorch,
  SiNumpy,
  SiPandas,
  SiNotion,
  SiSqlite,
  SiMysql,
} from "react-icons/si";
import { FaJava, FaCode, FaDatabase, FaTerminal } from "react-icons/fa";

export const ICON_MAP: Record<string, IconType> = {
  SiTypescript,
  SiJavascript,
  SiPython,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiNodedotjs,
  SiPostgresql,
  SiMongodb,
  SiGit,
  SiDocker,
  SiFigma,
  SiTensorflow,
  SiCplusplus,
  SiHtml5,
  SiCss3,
  SiFirebase,
  SiVercel,
  SiLinux,
  SiGraphql,
  SiRedis,
  SiRust,
  SiGo,
  SiKubernetes,
  SiPrisma,
  SiSvelte,
  SiVuedotjs,
  SiAmazon,
  SiGooglecloud,
  SiSupabase,
  SiNestjs,
  SiExpress,
  SiSwift,
  SiKotlin,
  SiFlutter,
  SiDart,
  SiPhp,
  SiRuby,
  SiOpenai,
  SiPytorch,
  SiNumpy,
  SiPandas,
  SiNotion,
  SiSqlite,
  SiMysql,
  FaJava,
  FaCode,
  FaDatabase,
  FaTerminal,
};

export const ICON_NAMES = Object.keys(ICON_MAP).sort();

export function resolveIcon(name: string | undefined): IconType {
  if (name && ICON_MAP[name]) return ICON_MAP[name];
  return FaCode;
}
